WebPractica02/WebPractica02/Models/consulta.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http.Json;
using System.Net.Http;
using System.Web;
using WebPractica02.Entity;


namespace WebPractica02.Models
{
    public class consultaModel
    {
        private string urlApi = ConfigurationManager.AppSettings["urlApi"];

        public List<consultaEntities> RealizarConsulta()
        {
            using (var client = new HttpClient())
            {
                var url = urlApi + "RealizarConsulta";
                var res = client.GetAsync(url).Result;
                return res.Content.ReadFromJsonAsync<List<consultaEntities>>().Result;
            }
        }

    }


}

WebPractica02/WebPractica02/Models/vehiculoModel.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http.Json;
using System.Net.Http;
using System.Web;
using WebPractica02.Entity;
using Newtonsoft.Json;

namespace WebPractica02.Models
{
    public class consulta
    {
        private string urlApi = ConfigurationManager.AppSettings["urlApi"];
        public string RegistroCarro(vehiculoEntities vehiculo)
        {
            using (var client = new HttpClient())
            {
                string url = urlApi + "RegistroCarro";
                JsonContent contenido = JsonContent.Create(vehiculo);
                using (HttpResponseMessage resp = client.PostAsync(url, contenido).Result)
                {
                    return resp.Content.ReadFromJsonAsync<string>().Result;
                }
            }
        }

    }
}

WebPractica02/WebPractica02/Models/vendedorModel.cs
using Newtonsoft.Json;
using System;
using System.Configuration;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using WebPractica02.Entity;

namespace WebPractica02.Models
{
    public class VendedorModel
    {
        private string urlApi = ConfigurationManager.AppSettings["urlApi"];

        public string RegistrarVendedor(vendedorEntities vendedor)
        {
            using (var client = new HttpClient())
            {
                string url = urlApi + "RegistrarVendedor";
                JsonContent contenido = JsonContent.Create(vendedor);
                using (HttpResponseMessage resp = client.PostAsync(url, contenido).Result)
                {
                    return resp.Content.ReadFromJsonAsync<string>().Result;
                }
            }
        }
    }
}

WebPractica02/WebPractica02/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPractica02.Entity;
using WebPractica02.Models;

namespace WebPractica02.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

WebPractica02/WebPractica02/Controllers/MostrarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPractica02.Models;

namespace WebPractica02.Controllers
{
    public class MostrarController : Controller
    {
        consultaModel model = new consultaModel();

        [HttpGet]
        public ActionResult RealizarConsulta()
        {
            var datos = model.RealizarConsulta();
            return View(datos);
        }


    }
}

WebPractica02/WebPractica02/Controllers/RegistrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebPractica02.Entity;
using WebPractica02.Models;

namespace WebPractica02.Controllers
{
    public class RegistrosController : Controller
    {
        [HttpGet]
        public ActionResult RegistroCarro()
        {
            ViewBag.Message = "Registre el Carro";

            return View();
        }

        [HttpPost]
        public ActionResult RegistroCarro(vehiculoEntities vehiculo)
        {
            consulta model = new consulta();

            if (ModelState.IsValid) // Verifica si hay errores en el modelo
            {
                model.RegistroCarro(vehiculo);
                ViewBag.ConfirmationMessage = "Vehiculo registrado con éxito";
            }
            else
            {
                ViewBag.ErrorMessage = "Se encontraron errores en el formulario. Corríjalos antes de continuar.";
            }

            return View();
        }

        [HttpGet]
        public ActionResult RegistroVendedores()
        {
            ViewBag.Message = "Registre el vendedor";

            return View();
        }

        [HttpPost]
        public ActionResult RegistroVendedores(vendedorEntities vendedor)
        {
            VendedorModel model = new VendedorModel();

            if (ModelState.IsValid) // Verifica si hay errores en el modelo
            {
                model.RegistrarVendedor(vendedor);
                ViewBag.ConfirmationMessage = "Vendedor registrado con éxito";
            }
            else
            {
                ViewBag.ErrorMessage = "Se encontraron errores en el formulario. Corríjalos antes de continuar.";
            }

            return View();
        }
    }
}

WebPractica02/WebPractica02/Views/Home/index.cshtml
@{
    ViewBag.Title = "index";
}

<h2>index</h2>

WebPractica02/WebPractica02/Views/Mostrar/RealizarConsulta.cshtml
@model IEnumerable<WebPractica02.Entity.consultaEntities>

@{
    ViewBag.Title = "RealizarConsulta";
}

<h2>Consulta</h2>
<section class="h-100">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
                <div class="card card-registration my-4">
                    <div class="row g-0">
                        <div class="col-xl-6 d-none d-xl-block">
                            <div class="d-flex justify-content-center">
                                @using (Html.BeginForm("RealizarConsulta", "Mostrar", FormMethod.Get))
                                {
                                    <h3 class="mb-5 text-uppercase">Consulta de Vehículos</h3>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="mb-4">
                                                <label for="cedula">Cedula</label>
                                                @Html.TextBox("Cedula", null, new { @class = "form-control", type = "text" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="mb-4">
                                                <label for="cedula">Nombre</label>
                                                @Html.TextBox("Nombre", null, new { @class = "form-control", type = "text" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="mb-4">
                                                <label for="marca">Marca</label>
                                                @Html.TextBox("Marca", null, new { @class = "form-control", type = "text" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="mb-4">
                                                <label for="modelo">Modelo</label>
                                                @Html.TextBox("Modelo", null, new { @class = "form-control", type = "text" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-4">
                                            <label for="precio">Precio</label>
                                            @Html.TextBox("Precio", null, new { @class = "form-control", type = "number" })
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-end pt-3">
                                        <button type="submit" class="btn btn-warning btn-lg">Buscar</button>
                                    </div>
                                }
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="card-body p-md-5 text-black">
                                <h3 class="mb-5 text-uppercase">Consulta de Vehículos</h3>
                                @if (Model != null && Model.Any())
                                {
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Cedula</th>
                                                    <th>NombreVendedor</th>
                                                    <th>Marca</th>
                                                    <th>Modelo</th>
                                                    <th>Precio</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td>@item.Cedula</td>
                                                        <td>@item.Nombre</td>
                                                        <td>@item.Marca</td>
                                                        <td>@item.Modelo</td>
                                                        <td>@item.Precio.ToString("C")</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                }
                                else
                                {
                                    <p class="alert">@ViewBag.Mensaje</p>
                                }


                                <div class="d-flex justify-content-end pt-3">
                                    <button type="button" class="btn btn-light btn-lg">Reset</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

WebPractica02/WebPractica02/Views/Registros/RegistroCarro.cshtml
@model WebPractica02.Entity.vehiculoEntities

@{
    ViewBag.Title = "RegistroCarro";
}

<section class="h-100 h-custom" style="background-color: #fff;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <div class="card rounded-3">
                    <img src="https://static.motor.es/fotos-noticias/2020/03/porsche-exclusive-manufaktur-911-turbo-s-indian-red-202065845-1584616347_1.jpg"
                         class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                         alt="Sample photo">
                    <div class="card-body p-4 p-md-5">
                        <div class="d-flex justify-content-center">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Registrar Vehiculo</h3>
                        </div>
                        @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                        {
                            <p class="alert alert-danger">@ViewBag.ErrorMessage</p>
                        }

                        @if (!string.IsNullOrEmpty(ViewBag.ConfirmationMessage))
                        {
                            <p class="alert alert-success">@ViewBag.ConfirmationMessage</p>
                        }
                        @using (Html.BeginForm("RegistroCarro", "Registros", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label for="marca">Marca</label>
                                @Html.TextBoxFor(model => model.Marca, new { @class = "form-control mw-100" })
                            </div>
                            <div class="form-group">
                                <label for="modelo">Modelo</label>
                                @Html.TextBoxFor(model => model.Modelo, new { @class = "form-control mw-100" })
                            </div>
                            <div class="form-group">
                                <label for="color">Color</label>
                                @Html.TextBoxFor(model => model.Color, new { @class = "form-control mw-100" })
                            </div>
                            <div class="form-group">
                                <label for="precio">Precio</label>
                                @Html.TextBoxFor(model => model.Precio, new { @class = "form-control mw-100" })
                            </div>
                            <div class="form-group">
                                <label for="vendedor">VendedorID</label>
                                @Html.TextBoxFor(model => model.Vendedor, new { @type = "number", @class = "form-control mw-100" })
                            </div>
                            <div class="d-flex justify-content-center mt-4">
                                <button type="submit" class="btn btn-danger btn-lg">Registrar</button>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

WebPractica02/WebPractica02/Views/Registros/RegistroVendedores.cshtml
@model WebPractica02.Entity.vendedorEntities

@{
    ViewBag.Title = "RegistroVendedores";
}

<main>
    <section class="" style="background-color: #fff;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-9">
                    <h1 class="text-black mb-4 text-center mt-4">Registrar Vendedor</h1>
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body">
                            @using (Html.BeginForm("RegistroVendedores", "Registros", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken() <!-- Agrega el token anti-falsificación de solicitudes POST -->
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">
                                        <h6 class="mb-0">Cedula</h6>
                                    </div>
                                    <div class="col-md-9 pe-5">
                                        @Html.TextBoxFor(model => model.Cedula, new { @class = "form-control form-control-lg", placeholder = "Cedula" })
                                      
                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center py-3">
                                    <div class="col-md-3 ps-5">
                                        <h6 class="mb-0">Nombre</h6>
                                    </div>
                                    <div class="col-md-9 pe-5">
                                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control form-control-lg", placeholder = "Nombre" })
                                  
                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center py-3">
                                    <div class="col-md-3 ps-5">
                                        <h6 class="mb-0">Email</h6>
                                    </div>
                                    <div class="col-md-9 pe-5">
                                        @Html.TextBoxFor(model => model.Correo, new { @class = "form-control form-control-lg", placeholder = "example@example.com" })
                               
                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center py-3">
                                    <div class="col-md-3 ps-5">
                                        <h6 class="mb-0">Estado</h6>
                                    </div>
                                    <div class="col-md-9 pe-5">
                                        @Html.DropDownListFor(model => model.Estado, new List<SelectListItem>
                                        {
                                            new SelectListItem { Text = "Activo", Value = "True" },
                                            new SelectListItem { Text = "Inactivo", Value = "False" }
                                        }, new { @class = "form-select form-select-lg" })
                                    </div>
                                    @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                                    {
                                        <p class="alert alert-danger">@ViewBag.ErrorMessage</p>
                                    }

                                    @if (!string.IsNullOrEmpty(ViewBag.ConfirmationMessage))
                                    {
                                        <p class="alert alert-success">@ViewBag.ConfirmationMessage</p>
                                    }
                                </div>
                                <hr class="mx-n3">
                                <div class="d-flex justify-content-center">
                                    <button type="submit" class="btn btn-primary btn-lg">Registrar</button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

WebPractica02/WebPractica02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("index", "Home")">Nombre de la aplicación</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Alternar navegación">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("RegistroVendedores", "Registros")">Registro Vendedores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("RegistroCarro", "Registros")">Registro de Vehiculos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("RealizarConsulta", "Mostrar")">Consulta Vehiculos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>